version: '2'
services:
  phpserver:
    image: uselagoon/php-8.3-cli:23.12.0
    volumes:
      - .:/app:delegated
    environment:
      # To enable xdebug: XDEBUG_ENABLE=true docker-compose up -d phpserver
      XDEBUG_ENABLE: ${XDEBUG_ENABLE:-}
