name: Release

on:
  push:
    tags:
      - '*'
    branches:
      - main

permissions:
  contents: write

jobs:
  #;< RELEASEDRAFTER
  release-drafter:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #;> RELEASEDRAFTER
  #;< PHP
  release-php:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - uses: php-actions/composer@v6
        #;< PHP_PHAR
      - name: Build and test
        run: composer build && ./.build/php-command.phar | grep -q "?"
        #;> PHP_PHAR
      - name: Get Tag Name
        id: get-version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            #;< PHP_PHAR
            ./.build/php-command.phar
            #;> PHP_PHAR
            #;< !PHP_PHAR
            php-script
            #;> !PHP_PHAR
  #;> PHP
  #;< NODEJS
  release-nodejs:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run build
  #;> NODEJS
